version: '3'
services:
  server:
    image: node:alpine
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=db
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - database
    command: /bin/sh -c "npm i && npm run dev"

  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: