version: '3'
services:
  server:
    image: node:alpine
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - database
    command: /bin/sh -c "npm i && npm run dev"

  database:
    image: postgres

volumes:
  database: